import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Video, Upload, BarChart3 } from 'lucide-react';
import { toast } from 'sonner';
import { useNavigate } from 'react-router-dom';
import { createPageUrl } from './utils';

import VideoUploader from '../components/video/VideoUploader';
import ProcessingQueue from '../components/video/ProcessingQueue';

export default function AdminDashboard() {
    const navigate = useNavigate();
    const queryClient = useQueryClient();

    const { data: videos = [], isLoading } = useQuery({
        queryKey: ['videos'],
        queryFn: () => base44.entities.Video.list('-created_date', 100)
    });

    const processVideoMutation = useMutation({
        mutationFn: async (video) => {
            // TODO: Call backend function when enabled
            // For now, simulate processing with AI metadata generation
            
            toast.info('Processing video... This will use your backend function when enabled.');
            
            // Simulate AI analysis
            const mockTranscript = `This is a sample transcript for "${video.title}". In a real implementation, this would be generated by AssemblyAI. The video discusses important business topics including leadership, communication skills, and team management.`;
            
            const aiAnalysis = await base44.integrations.Core.InvokeLLM({
                prompt: `Analyze this video title and generate metadata:\nTitle: ${video.title}\n\nGenerate a professional title, description with hashtags, and categorize by topics (Human Relations, Leadership, Communication, Management, Training). Also suggest 2-3 short clips (2-5 min each) that would be valuable.`,
                response_json_schema: {
                    type: 'object',
                    properties: {
                        title: { type: 'string' },
                        description: { type: 'string' },
                        topics: { type: 'array', items: { type: 'string' } },
                        hashtags: { type: 'array', items: { type: 'string' } }
                    }
                }
            });

            await base44.entities.Video.update(video.id, {
                ...aiAnalysis,
                transcript_text: mockTranscript,
                status: 'needs_review',
                youtube_video_id: 'dQw4w9WgXcQ' // Mock ID
            });

            // Create sample clips
            const clipData = [
                {
                    video_id: video.id,
                    title: `Key Insights: ${aiAnalysis.title}`,
                    description: 'Essential takeaways from this training session',
                    start_time: 30,
                    end_time: 210,
                    duration: 180,
                    topics: aiAnalysis.topics.slice(0, 2),
                    confidence_score: 0.92,
                    status: 'suggested'
                },
                {
                    video_id: video.id,
                    title: `Practical Tips: ${aiAnalysis.topics[0] || 'Leadership'}`,
                    description: 'Actionable strategies you can implement today',
                    start_time: 240,
                    end_time: 480,
                    duration: 240,
                    topics: [aiAnalysis.topics[0] || 'Leadership'],
                    confidence_score: 0.88,
                    status: 'suggested'
                }
            ];

            await base44.entities.Clip.bulkCreate(clipData);
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['videos'] });
            toast.success('Video processed! Ready for review.');
        },
        onError: (error) => {
            toast.error('Processing failed: ' + error.message);
        }
    });

    const stats = {
        total: videos.length,
        pending: videos.filter(v => v.status === 'pending').length,
        processing: videos.filter(v => v.status === 'processing').length,
        needsReview: videos.filter(v => v.status === 'needs_review').length,
        approved: videos.filter(v => v.status === 'approved').length
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-6">
            <div className="max-w-7xl mx-auto">
                <div className="mb-8">
                    <h1 className="text-4xl font-bold text-gray-900 mb-2">Video Processing Dashboard</h1>
                    <p className="text-gray-600">Upload, process, and review training videos</p>
                </div>

                {/* Stats */}
                <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
                    <div className="bg-white rounded-lg p-4 border">
                        <div className="text-2xl font-bold text-gray-900">{stats.total}</div>
                        <div className="text-sm text-gray-600">Total Videos</div>
                    </div>
                    <div className="bg-blue-50 rounded-lg p-4 border border-blue-200">
                        <div className="text-2xl font-bold text-blue-700">{stats.pending}</div>
                        <div className="text-sm text-blue-600">Pending</div>
                    </div>
                    <div className="bg-yellow-50 rounded-lg p-4 border border-yellow-200">
                        <div className="text-2xl font-bold text-yellow-700">{stats.needsReview}</div>
                        <div className="text-sm text-yellow-600">Needs Review</div>
                    </div>
                    <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                        <div className="text-2xl font-bold text-green-700">{stats.approved}</div>
                        <div className="text-sm text-green-600">Approved</div>
                    </div>
                    <div className="bg-purple-50 rounded-lg p-4 border border-purple-200">
                        <div className="text-2xl font-bold text-purple-700">{stats.processing}</div>
                        <div className="text-sm text-purple-600">Processing</div>
                    </div>
                </div>

                <Tabs defaultValue="queue" className="space-y-6">
                    <TabsList>
                        <TabsTrigger value="queue" className="flex items-center gap-2">
                            <Video className="w-4 h-4" />
                            Processing Queue
                        </TabsTrigger>
                        <TabsTrigger value="upload" className="flex items-center gap-2">
                            <Upload className="w-4 h-4" />
                            Upload
                        </TabsTrigger>
                    </TabsList>

                    <TabsContent value="queue">
                        <ProcessingQueue
                            videos={videos}
                            onProcessVideo={(video) => processVideoMutation.mutate(video)}
                            onReviewVideo={(video) => navigate(createPageUrl('VideoReview') + '?id=' + video.id)}
                        />
                    </TabsContent>

                    <TabsContent value="upload">
                        <VideoUploader
                            onVideoUploaded={() => {
                                queryClient.invalidateQueries({ queryKey: ['videos'] });
                            }}
                        />
                    </TabsContent>
                </Tabs>
            </div>
        </div>
    );
}